name: zlapp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      
      - name: install dependencies
        run: |
          sudo apt-get install ca-certificates
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U requests[security]
    
      - name: run zlapp
        env:
          FUDAN_ID: ${{ secrets.FUDAN_ID }}
          FUDAN_PASSWORD: ${{ secrets.FUDAN_PASSWORD }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: python zlapp.py
