name: zlapp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python==4.5.4.60
          pip install easyocr pillow numpy
    
      - name: run zlapp
        env:
          FUDAN_ID: ${{ secrets.FUDAN_ID }}
          FUDAN_PASSWORD: ${{ secrets.FUDAN_PASSWORD }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: python zlapp.py
